### ISSUE TITLE
can't build with rust 1.85

### ISSUE THREAD

**Issue by RCasatta** [eternal-flame-AD/scrypt-opt#28]
From the readme it seems 1.85 should be compatible but I get

```
error[E0599]: no method named `get_disjoint_unchecked_mut` found for mutable reference `&mut [Align64<GenericArray<u8, ...>>]` in the current scope
   --> src/lib.rs:361:5
    |
361 |     scrypt_opt_derive::generate_target_variant("avx2")
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: the full type name has been written to '/home/casatta/git/lwk/scrypt-opt/target/debug/deps/scrypt_opt.long-type-2882859010421487208.txt'
    = note: consider using `--verbose` to print the full type name to the console
    = note: this error originates in the attribute macro `scrypt_opt_derive::generate_target_variant` (in Nightly builds, run with -Z macro-backtrace for more info)
help: there is a method `get_unchecked_mut` with a similar name
    |
361 |     get_unchecked_mut
    |

Some errors have detailed explanations: E0599, E0658, E0747.
For more information about an error, try `rustc --explain E0599`.
error: could not compile `scrypt-opt` (lib) due to 27 previous errors

```

**Comment by eternal-flame-AD** [comment]
Hi, yeah it seems like build isn't working on 1.85 .. I probably did something wrong testing the MSRV.

It seems the actual error comes from here:

```

error[E0599]: no method named `get_disjoint_unchecked_mut` found for mutable reference `&mut [Align64<generic_array::GenericArray<u8, UInt<UInt<UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>, B0>, B0>>>]` in the current scope
   --> src/lib.rs:456:24
    |
456 |                 self_v.get_disjoint_unchecked_mut([
    |                 -------^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
help: there is a method `get_unchecked_mut` with a similar name
    |
456 |                 self_v.get_unchecked_mut([
    |                        ~~~~~~~~~~~~~~~~~

```

Do you have a library to integrate with lower MSRV requirements? I plan on just bumping the MSRV to 1.86 unless you have special requirements where I can write a extension trait wrapper.

**Comment by RCasatta** [comment]
It's fine going 1.86
